### ISSUE TITLE
Missing something

### ISSUE THREAD

**Issue by airjoshb** [actions-on-google/apiai-transactions-nodejs#10]
I know I'm totally missing something simple, but I've spent a couple of days trying to get this to work. I've gone through each step, including creating a unique order number and redeploying, but when I ask it anything from the standard actions, I get "Could not request transactions...".

When I look into the Intents, there aren't any actions. App has all the info. Sim connects, get the response of the things to ask. Nothing happens. What am I missing?

**Comment by Fleker** [comment]
Have you updated this project recently with the new version of client library and code?

**Comment by airjoshb** [comment]
I cloned the repo again just now - in the transasctions zip file, the json for transaction_no_payment shows the below code, which doesn't appear to have a response other than "Could not request transactions check with no payment". Shouldn't there be an affirmative response or some other information? The other files seem similarly structured

`{
  "userSays": [
    {
      "id": "2fd866bc-3f2e-453f-8175-0c28ffab6821",
      "data": [
        {
          "text": "check transaction without payment"
        }
      ],
      "isTemplate": false,
      "count": 0
    }
  ],
  "id": "c21fbdc8-9438-46d7-8660-1dba2c8d7143",
  "name": "transaction_check_nopayment",
  "auto": true,
  "contexts": [],
  "responses": [
    {
      "resetContexts": false,
      "action": "transaction.check.no.payment",
      "affectedContexts": [],
      "parameters": [],
      "messages": [
        {
          "type": 0,
          "speech": "Could not request transactions check with no payment"
        }
      ]
    }
  ],
  "priority": 500000,
  "webhookUsed": true,
  "webhookForSlotFilling": false,
  "fallbackIntent": false,
  "events": []
}`

**Comment by smishra2** [comment]
Hey @airjoshb, the Transactions.zip file is used as the Dialogflow agent, and responses from there are mostly seen only in error cases. It assumes that the webhook has been deployed and responds appropriately (with a 200). Just to confirm, you have deployed the webhook code for this?

**Comment by taycaldwell** [comment]
Closing, as check transaction without payment is no longer supported by this sample.

If you are still running into issues with running the sample, feel free to re-open.
