### ISSUE TITLE
Braintree tokenizationParameters

### ISSUE THREAD

**Issue by xtraad** [actions-on-google/apiai-transactions-nodejs#13]
Everything works fine, except when I go to input Sandbox tokanisation parameters from Braintree for Google Payment method I get this error:

UnparseableJsonResponse: API Version 2: Failed to parse JSON response string with 'INVALID_ARGUMENT' error: "(payment_options.google_provided_options.tokenization_parameters) braintree:client_key: Cannot find field."

JSON looks like this

         ],
                "tokenizationParameters": {
                  "gateway": "braintree",
                  "braintree:sdkVersion": "1.4.0",
                  "braintree:apiVersion": "v1",
                  "braintree:merchantId": "66xxxxxxxt2",
                  "braintree:clientKey": "sandbox_9cxxxxxxxxxrzt2"
                }
              }
            },

Any ideas? Does it need to be specified as an array?

**Comment by taycaldwell** [comment]
Hi @xtraad,

For the Google payment method, your tokenization parameters in index.js would look something like:

```javascript
tokenizationParameters: {
    parameters: {
        "gateway": "braintree",
        "braintree:sdkVersion": "1.4.0",
        "braintree:apiVersion": "v1",
        "braintree:merchantId": "66xxxxxxxt2",
        "braintree:clientKey": "sandbox_9cxxxxxxxxxrzt2",
        "braintree:authorizationFingerprint": "sandbox_9cxxxxxxxxxrzt2"
    },
    tokenizationType: "PAYMENT_GATEWAY"
},
```

You will need to test using a device.

I will update the current sample with placeholder tokenizationParameters to avoid confusion of the expected format.

**Comment by taycaldwell** [comment]
Placeholder tokenizationParameters have been added to the sample.
