### ISSUE TITLE
can't get order to charge on stripe

### ISSUE THREAD

**Issue by cgilhoi** [actions-on-google/apiai-transactions-nodejs#14]
Able to create a token but can't grab it and charge.  Here is my code:

```
 app.post('/charge', function(req, res) {
  var stripeToken = req.body.stripeToken;
  var amount = 9;

  stripe.charges.create({
      source: stripeToken,
      currency: 'usd',
      amount: amount
  },
  function(err, charge) {
      if (err) {
          res.send(500, err);
      } else {
          res.send(204);
      }
  });
});
```

**Comment by taycaldwell** [comment]
This is more of a question about Stripes library than the provided sample.

Can you clarify what errors your running into when trying to make a charge with the provided code?

**Comment by tschaeff** [comment]
@cgilhoi I got it working with Stripe as shown here: https://gist.github.com/thorsten-stripe/9928b11dbf45980af058c3284aafd416

**Comment by thorsten-stripe** [comment]
@cgilhoi I got it working with Stripe as shown here: https://gist.github.com/thorsten-stripe/9928b11dbf45980af058c3284aafd416

And yes, the error message would be helpful 👍

**Comment by cgilhoi** [comment]
Yeah, I was finally able to get it to work too.  Next step is trying to assemble a cart.  Lots of work.  Do you have an app that does transactions in production?
________________________________
