### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by mohd7469** [actions-on-google/apiai-transactions-nodejs#18]
Transaction always fails when testing at google assistant on both queries 

- **check transaction with action payment.**

- **check transaction with google payment.**

what am i doing wrong ? i have enabled these transaction checkboxes on directory information

- [x] Do Your Actions use the Transactions API to perform transactions of physical goods?

- [x] Do your Actions use the Digital Purchase API to perform transactions of digital goods? 

**Response** 
`
{
  "status": 200,
  "headers": {
    "content-type": "application/json;charset=utf-8"
  },
  "body": {
    "payload": {
      "google": {
        "expectUserResponse": false,
        "richResponse": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "Transaction failed."
              }
            }
          ]
        }
      }
    }
  }
}
`

**Request** 
`{
  "responseId": "885a45db-3231-4b3b-bacd-0bd75fe4a882",
  "queryResult": {
    "queryText": "actions_intent_TRANSACTION_REQUIREMENTS_CHECK",
    "action": "transaction.check.complete",
    "parameters": {},
    "allRequiredParamsPresent": true,
    "fulfillmentText": "Failed to get transaction check results",
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            "Failed to get transaction check results"
          ]
        }
      }
    ],
    "outputContexts": [
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/actions_capability_screen_output"
      },
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/google_assistant_input_type_voice"
      },
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/actions_capability_audio_output"
      },
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/actions_capability_media_response_audio"
      },
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/actions_capability_web_browser"
      },
      {
        "name": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI/contexts/actions_intent_transaction_requirements_check",
        "parameters": {
          "text": "",
          "TRANSACTION_REQUIREMENTS_CHECK_RESULT": {
            "@type": "type.googleapis.com/google.actions.v2.TransactionRequirementsCheckResult",
            "resultType": "REGION_NOT_SUPPORTED"
          }
        }
      }
    ],
    "intent": {
      "name": "projects/transactions-3347e/agent/intents/fd16d86b-60db-4d19-a683-5b52a22f4795",
      "displayName": "transaction_check_complete"
    },
    "intentDetectionConfidence": 1,
    "languageCode": "en-gb"
  },
  "originalDetectIntentRequest": {
    "source": "google",
    "version": "2",
    "payload": {
      "isInSandbox": true,
      "surface": {
        "capabilities": [
          {
            "name": "actions.capability.SCREEN_OUTPUT"
          },
          {
            "name": "actions.capability.AUDIO_OUTPUT"
          },
          {
            "name": "actions.capability.WEB_BROWSER"
          },
          {
            "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
          }
        ]
      },
      "inputs": [
        {
          "rawInputs": [
            {
              "inputType": "VOICE"
            }
          ],
          "arguments": [
            {
              "extension": {
                "@type": "type.googleapis.com/google.actions.v2.TransactionRequirementsCheckResult",
                "resultType": "REGION_NOT_SUPPORTED"
              },
              "name": "TRANSACTION_REQUIREMENTS_CHECK_RESULT"
            },
            {
              "name": "text"
            }
          ],
          "intent": "actions.intent.TRANSACTION_REQUIREMENTS_CHECK"
        }
      ],
      "user": {
        "lastSeen": "2019-01-27T09:54:55Z",
        "locale": "en-GB",
        "userId": "ABwppHGvhOzu1IUi0FqS2EuaQ20hmyFnykYy7cmypDFkDswgm1Ema-omvioy8RFMR2JcnhBfJOiuV3QenKU-tFgq"
      },
      "conversation": {
        "conversationId": "ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI",
        "type": "ACTIVE",
        "conversationToken": "[]"
      },
      "availableSurfaces": [
        {
          "capabilities": [
            {
              "name": "actions.capability.SCREEN_OUTPUT"
            },
            {
              "name": "actions.capability.AUDIO_OUTPUT"
            },
            {
              "name": "actions.capability.WEB_BROWSER"
            }
          ]
        }
      ]
    }
  },
  "session": "projects/transactions-3347e/agent/sessions/ABwppHEPGOqKaE9QOPG21vBLOybYuFR2ygIQUYiyIsER6h-0YwAm_Y_J4iLvfe3l8U4I2HCyjjfLM2wXhnujinlI"
}`

**Comment by findzaatar** [comment]
@awais786327 

Based on what you've mentioned, you only are intending on using Physical goods (Transactions API) and not the Digital Goods (Digital Purchases API). Physical goods comprise of both [merchant-managed](https://developers.google.com/actions/transactions/physical/dev-guide-physical-custom) and [Google payments](https://developers.google.com/actions/transactions/physical/dev-guide-physical-gpay). You can read more about this in the [docs](https://developers.google.com/actions/transactions/).
