### ISSUE TITLE
tested in both Google Assistant App and simulator, I already get my test app isn’t responding right now. Try again soon.

### ISSUE THREAD

**Issue by kevingzhang** [actions-on-google/apiai-transactions-nodejs#3]
After "talk to my test app",
I get the welcome message. that's good.
then I type 

"check transaction without payment"

I got 
"my test app isn’t responding right now. Try again soon."

I can see the firebase function got hit, and output is correct:
===
Request headers: {"x-forwarded-for":"104.197.215.28","x-forwarded-proto":"https","accept-encoding":"gzip,deflate","user-agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_131)","host":"4af70e03.ngrok.io","content-length":"1536","content-type":"application/json; charset=UTF-8","accept":"*/*","connection":"close"}
Request body: {"originalRequest":{"source":"google","version":"2","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.SCREEN_OUTPUT"}]},"inputs":[{"rawInputs":[{"query":"check transaction without payment","inputType":"KEYBOARD"}],"arguments":[{"rawText":"check transaction without payment","textValue":"check transaction without payment","name":"text"}],"intent":"actions.intent.TEXT"}],"user":{"locale":"en-US","userId":"APhe68EA2Zw30mKTUcg4qIMNTb8Z"},"device":{},"conversation":{"conversationId":"1499924401422","type":"ACTIVE","conversationToken":"[]"}}},"id":"744a0c6a-0d59-4d3d-b100-e85157a913c8","timestamp":"2017-07-13T05:40:09.443Z","lang":"en","result":{"source":"agent","resolvedQuery":"check transaction without payment","speech":"","action":"transaction.check.no.payment","actionIncomplete":false,"parameters":{},"contexts":[{"name":"actions_capability_screen_output","parameters":{},"lifespan":0},{"name":"actions_capability_audio_output","parameters":{},"lifespan":0},{"name":"google_assistant_input_type_keyboard","parameters":{},"lifespan":0}],"metadata":{"intentId":"c21fbdc8-9438-46d7-8660-1dba2c8d7143","webhookUsed":"true","webhookForSlotFillingUsed":"false","nluResponseTime":5,"intentName":"transaction_check_nopayment"},"fulfillment":{"speech":"Could not request transactions check with no payment","messages":[{"type":0,"speech":"Could not request transactions check with no payment"}]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1499924401422"}
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug handleRequest: handler=[object Map]
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug extractData_
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug handleRequest: map
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug getIntent
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug getIntent_
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug invokeIntentHandler_: handler=[object Map], intent=transaction.check.no.payment
info: Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug key is id
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug name=transaction.check.no.payment
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug map of intents
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug checkForTransactionRequirements: transactionConfig=undefined, dialogState=undefined
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug fulfillTransactionRequirementsCheck_: transactionRequirementsSpec={}
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug buildResponse_: textToSpeech=PLACEHOLDER_FOR_TXN_REQUIREMENTS, expectUserResponse=true, noInputs=undefined
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug isSsml_: text=PLACEHOLDER_FOR_TXN_REQUIREMENTS
info: Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug doResponse_: response={"speech":"PLACEHOLDER_FOR_TXN_REQUIREMENTS","contextOut":[{"name":"_actions_on_google_","lifespan":100,"parameters":{}}],"data":{"google":{"expectUserResponse":true,"isSsml":false,"noInputPrompts":[],"systemIntent":{"intent":"actions.intent.TRANSACTION_REQUIREMENTS_CHECK","data":{"@type":"type.googleapis.com/google.actions.v2.TransactionRequirementsCheckSpec"}}}}}, responseCode=200
info: Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug isNotApiVersionOne_
Thu, 13 Jul 2017 05:40:10 GMT actions-on-google:debug Response {"speech":"PLACEHOLDER_FOR_TXN_REQUIREMENTS","contextOut":[{"name":"_actions_on_google_","lifespan":100,"parameters":{}}],"data":{"google":{"expectUserResponse":true,"isSsml":false,"noInputPrompts":[],"systemIntent":{"intent":"actions.intent.TRANSACTION_REQUIREMENTS_CHECK","data":{"@type":"type.googleapis.com/google.actions.v2.TransactionRequirementsCheckSpec"}}}}}
info: Execution took 25 ms, user function completed successfully

===

If I test in Api.ai page, I got response with Json:
===
{
  "id": "646e408e-c713-4352-81c2-cc0b1baa5e83",
  "timestamp": "2017-07-13T05:43:24.672Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "check transaction without payment",
    "action": "transaction.check.no.payment",
    "actionIncomplete": false,
    "parameters": {},
    "contexts": [
      {
        "name": "_actions_on_google_",
        "parameters": {},
        "lifespan": 100
      }
    ],
    "metadata": {
      "intentId": "c21fbdc8-9438-46d7-8660-1dba2c8d7143",
      "webhookUsed": "true",
      "webhookForSlotFillingUsed": "false",
      "webhookResponseTime": 342,
      "intentName": "transaction_check_nopayment"
    },
    "fulfillment": {
      "speech": "PLACEHOLDER_FOR_TXN_REQUIREMENTS",
      "messages": [
        {
          "type": 0,
          "speech": "PLACEHOLDER_FOR_TXN_REQUIREMENTS"
        }
      ],
      "data": {
        "google": {
          "expect_user_response": true,
          "is_ssml": false,
          "no_input_prompts": [],
          "system_intent": {
            "intent": "actions.intent.TRANSACTION_REQUIREMENTS_CHECK",
            "data": {
              "type": "type.googleapis.com/google.actions.v2.TransactionRequirementsCheckSpec"
            }
          }
        }
      }
    },
    "score": 1
  },
  "status": {
    "code": 200,
    "errorType": "success"
  },
  "sessionId": "e5410227-c5bf-499a-87ae-5d70a06b0ee2"
}
===

I tried both on mobile app and simulator, the same result. 
is there any configuration mistake on my side?

**Comment by smishra2** [comment]
Have you enabled the Transactions APIs at the bottom of the App Info section of your project in the [Actions Console](console.actions.google.com)?

**Comment by kevingzhang** [comment]
It is enabled. but I cannot reproduce this issue any longer. After few minutes ( more than 10 + minutes), the server response correctly.
I think the reason could be somewhere between my Ngrok, internet connection or firebase serve local problem.
