### ISSUE TITLE
About order-update

### ISSUE THREAD

**Issue by aotarola** [actions-on-google/apiai-transactions-nodejs#4]
Hi, I'm trying to send order-updates to my Android device after the order is created, but I keep getting the error

```json
{ "error":
   { "code": 500,
     "message": "Order 1113 could not be found for project testagent-14102.",
     "status": "INTERNAL" 
    } 
}
```

I have the Conversations API enabled on my Google cloud project. 

The part I don't get is, where do Google Transactions store the Order record? Does it live in the user google account or in the Google cloud project?

**Comment by smishra2** [comment]
Orders are stored by user. User's will be able to check their order history in their Assistant settings on a mobile device.

**Comment by Klervix** [comment]
Hi,
I've the same problem! Did you find a solution?

Thank you!

**Comment by lamer-x11** [comment]
Make sure that your update request contains the `isInSandbox` parameter and its value matches the order type.

**Comment by findzaatar** [comment]
The sample has been updated and this issue is no longer an issue
