### ISSUE TITLE
Not able to make this code work

### ISSUE THREAD

**Issue by joshash1102** [actions-on-google/apiai-transactions-nodejs#9]
Followed the instruction in README.md step by step.
Using backend code and dialog-flow code as is in the repository, we set up the Assistant App and tested out the flow:

check transaction without payment => Get Delivery Address => {Select Address} => confirm transaction

The app works till {Select Address} but fails after ‘confirm transaction’ with the error:

expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.other_items[0]: adjustment must not have quantity defined.

**Comment by cgilhoi** [comment]
I got stuck on the same step.  Works until confirm transaction.  I expected it to populate with the generic information in the transactionDecision function, but exited out saying app wasn't responding.  Wasn't able to figure out the error from firebase functions:log

Did you figure this out or get any help?

**Comment by kojoduncan** [comment]
Same here getting a bunch of errors with this code.

"sharedDebugInfo": [
      {
        "name": "ResponseValidation",
        "subDebugEntry": [
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.other_items[0]: adjustment must not have quantity defined.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.other_items[1]: adjustment must not have quantity defined.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0]: line item type must be REGULAR.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1]: line item type must be REGULAR.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].sub_lines[0]: line item must not have more than $0 note(s).",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2]: line item type must be REGULAR.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2].sub_lines[0]: line item type must be REGULAR.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2].sub_lines[0].line_items[3]: line item type must be REGULAR.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2]: subtotal price is not sum of regular lineItems. Expected-> Sum of line item price: units: 0 nanos: 0 currency:  Actual-> Provided total price: units: 32 nanos: 220000000 currency: USD.",
            "name": "MalformedResponse"
          },
          {
            "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0]: payment options must be specified when the total price is non-zero.",
            "name": "MalformedResponse"
          }
        ]
      }
    ]
  },
  "errors": [
    [
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.other_items[0]: adjustment must not have quantity defined.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.other_items[1]: adjustment must not have quantity defined.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0]: line item type must be REGULAR.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1]: line item type must be REGULAR.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].sub_lines[0]: line item must not have more than $0 note(s).",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2]: line item type must be REGULAR.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2].sub_lines[0]: line item type must be REGULAR.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2].sub_lines[0].line_items[3]: line item type must be REGULAR.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0].line_items[2]: subtotal price is not sum of regular lineItems. Expected-> Sum of line item price: units: 0 nanos: 0 currency:  Actual-> Provided total price: units: 32 nanos: 220000000 currency: USD.",
        "name": "MalformedResponse"
      },
      {
        "debugInfo": "expected_inputs[0].possible_intents[0].input_value_data.transaction_decision_value_spec.proposed_order.cart.line_items[0].sub_lines[0].line_items[1].sub_lines[0]: payment options must be specified when the total price is non-zero.",
        "name": "MalformedResponse"
      }
    ]
  ]
}

**Comment by taycaldwell** [comment]
These bugs have been fixed. Please re-run the sample and open a new issue if you are running into any other issues.
